CP4D_Credentials:
  url:
  username:
  password:
Project: noah-test-space
Namespace: mlops
Model:
  name: noah-test-model
  type: scikit-learn_0.22
  path: models/svm.tar.gz
  software_spec: scikit-learn_0.22-py3.6
  problem_type: BINARY_CLASSIFICATION
  dataset_name: val_breast_cancer.csv # validation data set
  label_column: target
