# CP4D username and password are expected to be contained in the 
# env vars CP4D_USERNAME and CP4D_PASSWORD
CP4D:
  url:
  project_name: mlops
  deployment_space_name: noah-test-space
Model:
  model_name: noah-test-model
  model_path: python/models/svm.tar.gz # relative to project root
  model_type: scikit-learn_0.22
  software_spec: scikit-learn_0.22-py3.6
  problem_type: BINARY_CLASSIFICATION
  dataset_name: val_breast_cancer.csv # validation data set
  label_column: target
